spring:
  application:
    name: standing-orders-services
  profiles:
    active: "dev"
  jmx:
    enabled: false

debug: false
server:
  port: 8080

management:

  server:
    port: 8080
  endpoints:
    access.default: read-only
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    defaults:
      enabled: true
    git:
      enabled: true
      mode: full
    env:
      enabled: true
    build:
      enabled: true
springdoc:

  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
artifact:
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'  
sentry:
  dsn: ${SENTRY_DSN_STANDING_ORDERS_SERVICES}
  send-default-pii: true    
  # Enable sending logs to Sentry
  logs:
    enabled: true
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  # Set profile-session-sample-rate to 1.0 to profile 100% of profile sessions.
  profile-session-sample-rate: 1.0
  # Set profile-lifecycle to trace to automatically start and stop
  # profiling when a transaction starts and finishes.
  profile-lifecycle: TRACE  