name: maven-deploy
on:
  push:
    branches:
      - master
      - develop
      - "releases/**"
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  mvn-deploy:
    uses: rock-hu/workflows/.github/workflows/maven-deploy.yaml@master
    # rock-hu/workflows/.github/workflows/maven-deploy.yaml
